permalink: pretty
paginate: 5
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'run', '_drafts/*.R', '_drafts/*.Rmd']
excerpt_separator: <!--more-->

production_url: http://kevinbm.github.io

markdown: redcarpet-pygments
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
hightlighter: pygments

  

  




