hightlighter: pygments
permalink: pretty
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'run', 'blog/_drafts/*.R', 'blog/_drafts/*.Rmd']
excerpt_separator: <!--more-->
categories: [projectk, postk, publick]
markdown: kramdown
kramdown:
  input: GFM
  
# edit here to achieve your personal greatness
url: http://kevinbm.github.io
baseurl: /
author: Kevin Bello
description: Personal information and blog
avatar: profile.png
email: kbellom@uni.pe
github: kevinbm




  


  

  




