permalink: pretty
paginate: 5
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'run', '_drafts/*.R', '_drafts/*.Rmd']


production_url: http://kevinbm.github.io

markdown: redcarpet-pygments

hightlighter: pygments

  

  




